site_name: Curioustools # Website name(comes on top left in nav bar)
site_description: Google certified Associate Android Dev #browser tab tooltip text
site_author: Ansh Sachdeva(root-ansh) #don't know where does it shows

#Header
#repo_name: 'root-ansh/curioustools'
#repo_url: 'https://github.com/root-ansh/curioustools'
#tabs:{a,b,c} X # Tabs are generated automatically using nav's topmost division and theme's  extras -tabs: true feature

#Footer
extra:
  social:
    - type: 'github'
      link: 'https://github.com/root-ansh'
    - type: 'twitter'
      link: 'https://twitter.com/root_ansh'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/anshsachdevaprofessional/'

copyright: Copyright &copy; 2019 <a href="https://www.linkedin.com/in/anshsachdevaprofessional/">Ansh Sachdeva</a>

#Theming
theme:
    name: material
    palette:
        primary: 'white'
        accent: 'green'
        #links_color : 'green' #todo, this is not the correct solution
        
    logo: img/logo/logo.svg
    favicon: 'assets/images/favicon.ico'

    feature:
        tabs: true    

    language: 'en'    
    extra:
        search:
            language: 'en'
            tokenizer: '[\s\-\.]+'
    
    #custom_dir: no_toc #not working
        
    #toc:
        # disable: true # todo, this is not working. expected this to remove table of contents
#extra_css:
#    - 'stylesheets/extra.css' # for disabling toc # not working

markdown_extensions:
    - admonition  # fancy error/note blocks
    - codehilite: # cool code blocks with numbers/ nested code tabs(like that of google java/kotlin!!!:D)
        linenums: true
    - meta
    - toc:
        permalink: "#"
    
    #- extra:   # adds disquos comment section on the bottom of each page
        #disqus: 'your-shortname' # todo, not working.
    
    # ---- all very useless pymdownx extensions that i need to read more, but mostly are useless---
    #- pymdownx.arithmatex
    #- pymdownx.betterem:
    #    smart_enable: all
    #- pymdownx.caret
    #- pymdownx.critic
    #- pymdownx.details
    #- pymdownx.emoji:
    #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
    #- pymdownx.inlinehilite
    #- pymdownx.magiclink
    #- pymdownx.mark
    #- pymdownx.smartsymbols
    #- pymdownx.superfences
    #- pymdownx.tasklist:
    #    custom_checkbox: true
    #- pymdownx.tilde 



nav:
    - About Me: index.md
    
    - Education Details:
        - Introduction: tab_edu/edu_details.md
        
    - Work Experience: 
        - Introduction: tab_work_exp/work_exp.md

    - Portfolio:
        - Introduction: tab_projects/project_summary.md
        - SelfNotes : tab_projects/project_selfnotes.md

    - Blogs:
        - Introduction : tab_blogs/blog_summary.md
        - Web:
            Mkdocs:
                - tab_blogs/web/basic_syntax.md
            
            

